### ISSUE TITLE
Phone number not found in context, while selecting razorpay payment method

### ISSUE THREAD

**Issue by Kartik18g** [SGFGOV/medusa-payment-razorpay#10]
I've followed the readme instructions, but when i select razorpay option i'm getting this error.
```{
    "code": "cart_incompatible_state",
    "type": "payment_authorization_error",
    "message": "Phone number not found in context"
}
```
I'm not sure what's wrong, seems something with the plugin.

**Comment by thakkaryash21** [comment]
@Kartik18g I am facing the same error. How did you resolve it?
