### ISSUE TITLE
order_id is missing in initiatePayment & updatePayment methods

### ISSUE THREAD

**Issue by sumanchy88** [SGFGOV/medusa-payment-razorpay#17]
`order_id` is required to pass in methods`initiatePayment` & `updatePayment` through PaymentProcessorContext which is coming from `@medusajs/medusa` library.
As of current, `@medusajs/medusa` interface `PaymentProcessorContext` does not hold the field `order_id`. 
Is there way it can be override and pass through the mentioned method. 

Please refer the open ticket in medusa [Bug:6511](https://github.com/medusajs/medusa/issues/6511)

**Comment by sandipan-s** [comment]
@SGFGOV could you please help in figuring out this issue ?

**Comment by SGFGOV** [comment]
The issue is that your are not filling the phone number during checkout

**Comment by SGFGOV** [comment]
Check your client plz

**Comment by manishkumar212111** [comment]
@SGFGOV @sandipan-s @sumanchy88 have you found any solution for this ?

**Comment by sumanchy88** [comment]
@manishkumar212111 -
For me it started working. Just check if user is already exists in Razorpay or not. Try with some different email.

**Comment by SGFGOV** [comment]
It's not compatible with older versions of the plugin

**Comment by manishkumar212111** [comment]
@sumanchy88 @SGFGOV unable to retrieve customer from cart
error:   unable to find razorpay customer
While adding product to cart

**Comment by SGFGOV** [comment]
You are trying to login and checkout without saving customer

**Comment by manishkumar212111** [comment]
> You are trying to login and checkout without saving customer

Steps:  Creating new customer=> Adding product into cart => then trying checkout

**Comment by manishkumar212111** [comment]
> You are trying to login and checkout without saving customer

@SGFGOV Did you get time to look into this issue. I am planning to move to production but unable to make payment using razorpay

**Comment by SGFGOV** [comment]
Let's get on a video call?

**Comment by manishkumar212111** [comment]
> Let's get on a video call?

https://meet.google.com/xgk-damm-vug

**Comment by manishkumar212111** [comment]
> Let's get on a video call?

Hey, If possible can we connect now

**Comment by youreachedrahat** [comment]
@manishkumar212111 
![image](https://github.com/SGFGOV/medusa-payment-razorpay/assets/70068895/5bd6fcd9-4748-4c95-af67-d2fa41e80098)

**Comment by ltejaram** [comment]
@manishkumar212111 @SGFGOV  is there a way to do it in guest mode (if customer havent logged in).
i am getting the following error while doing it in guest mode:
warn:    no customer billing found
info:    the creating  customer  in razopay
error:   unable to create customer in the razorpay payment processor
error:   unable to find razorpay customer

**Comment by SGFGOV** [comment]
It's already there.. the cart object has all.this info

**Comment by SGFGOV** [comment]
Please upgrade

**Comment by youreachedrahat** [comment]
@SGFGOV upgrade what? The payment library? I believe it is already on latest version

**Comment by SGFGOV** [comment]
please check the docs, you need to ensure that you send the phone number via cart.billing_address
