### ISSUE TITLE
Capturing payments

### ISSUE THREAD

**Issue by Nadeem34513** [SGFGOV/medusa-payment-razorpay#8]
Heyy,
So I have been testing this plugin for couple of days now and i found out that after a successful payment the store admin have to manually capture the payment from the dashboard. The work around i did was just calling the `capturePayment` method inside the `authorizePayment` , this would change the status to `captured` in the razorpay dashboard but it is still `Awaiting payment` in the admin dashboard and the button to `capture` still exists.

I'm not sure but I'm guessing it has to do with events and subscription

Have you found a way to work it out?

**Comment by liho00** [comment]
@SGFGOV Hi, can I have the discord channel link?

**Comment by rohanpadwalkar** [comment]
> [@SGFGOV](https://github.com/SGFGOV) Hi, can I have the discord channel link?
> 
> @Nadeem34513 Could you help to share the example of auto capturing payment?
> 
> Thanks in advance!

below resolved my issue.
```
options: {
            key_id: process?.env?.RAZORPAY_ID,
            key_secret: process?.env?.RAZORPAY_SECRET,
            razorpay_account: process?.env?.RAZORPAY_ACCOUNT,
            automatic_expiry_period: 30 /* any value between 12minuts and 30 days expressed in minutes*/,
            manual_expiry_period: 20,
            refund_speed: "normal",
            webhook_secret: process?.env?.RAZORPAY_WEBHOOK_SECRET,
            auto_capture: true  <-----------------
          }
```
